// Page2 Section1 Code2
export default {
	contents: [
		// 1行目
		[
			{
				id: "ccode2-1-1",
				text: "{",
				color: "emerald",
				indent: "",
				space: false,
			},
			{
				id: "ccode2-1-2",
				text: "this",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "ccode2-1-3",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "ccode2-1-4",
				text: "state",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "ccode2-1-5",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "ccode2-1-6",
				text: "x",
				color: "red",
				indent: "",
				space: true,
			},
			{
				id: "ccode2-1-7",
				text: "===",
				color: "white",
				indent: "",
				space: true,
			},
			{
				id: "ccode2-1-8",
				text: "0",
				color: "yellow",
				indent: "",
				space: true,
			},
			{
				id: "ccode2-1-9",
				text: "? \"",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "ccode2-1-10",
				text: "Learn React",
				color: "green",
				indent: "",
				space: false,
			},
			{
				id: "ccode2-1-11",
				text: "\" : \"",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "ccode2-1-12",
				text: "Try React",
				color: "green",
				indent: "",
				space: false,
			},
			{
				id: "ccode2-1-13",
				text: "\"",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code2-1-14",
				text: "}",
				color: "emerald",
				indent: "",
				space: false,
			},
		],
	],
}
