// Page2 Section1 Code3
export default {
	contents: [
		// 1行目
		[
			{
				id: "code3-1-1",
				text: "func",
				color: "blue",
				indent: "",
				space: false,
			},
			{
				id: "code3-1-2",
				text: "() {",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 2行目
		[
			{
				id: "code3-2-1",
				text: "this",
				color: "red",
				indent: "indent1",
				space: false,
			},
			{
				id: "code3-2-2",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-3",
				text: "state",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-4",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-5",
				text: "x",
				color: "red",
				indent: "",
				space: true,
			},
			{
				id: "code3-2-6",
				text: "===",
				color: "white",
				indent: "",
				space: true,
			},
			{
				id: "code3-2-7",
				text: "0",
				color: "yellow",
				indent: "",
				space: true,
			},
			{
				id: "code3-2-8",
				text: "? (",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-9",
				text: "this",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-9a",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-10",
				text: "setState",
				color: "blue",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-11",
				text: "({",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-12",
				text: "x",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-12a",
				text: ":",
				color: "white",
				indent: "",
				space: true,
			},
			{
				id: "code3-2-13",
				text: "1",
				color: "yellow",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-14",
				text: "})) : (",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-15",
				text: "this",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-16",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-17",
				text: "setState",
				color: "blue",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-18",
				text: "({",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-19",
				text: "x",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-20",
				text: ":",
				color: "white",
				indent: "",
				space: true,
			},
			{
				id: "code3-2-21",
				text: "0",
				color: "yellow",
				indent: "",
				space: false,
			},
			{
				id: "code3-2-22",
				text: "}));",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 3行目
		[
			{
				id: "code3-3-1",
				text: "}",
				color: "white",
				indent: "",
				space: false,
			},
		],
	],
}
