// Page2 Section1 Code5
export default {
	contents: [
		// 1行目
		[
			{
				id: "code5-1-1",
				text: "import",
				color: "purple",
				indent: "",
				space: true,
			},
			{
				id: "code5-1-2",
				text: "React",
				color: "red",
				indent: "",
				space: true,
			},
			{
				id: "code5-1-3",
				text: "from",
				color: "purple",
				indent: "",
				space: true,
			},
			{
				id: "code5-1-4",
				text: "'",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-1-5",
				text: "react",
				color: "green",
				indent: "",
				space: false,
			},
			{
				id: "code5-1-6",
				text: "';",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 2行目
		[],
		// 3行目
		[
			{
				id: "code5-3-1",
				text: "class",
				color: "purple",
				indent: "",
				space: true,
			},
			{
				id: "code5-3-2",
				text: "App",
				color: "orange",
				indent: "",
				space: true,
			},
			{
				id: "code5-3-3",
				text: "extends",
				color: "purple",
				indent: "",
				space: true,
			},
			{
				id: "code5-3-4",
				text: "React",
				color: "orange",
				indent: "",
				space: false,
			},
			{
				id: "code5-3-5",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-3-6",
				text: "Component",
				color: "orange",
				indent: "",
				space: true,
			},
			{
				id: "code5-3-7",
				text: "{",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 4行目
		[],
		// 5行目
		[
			{
				id: "code5-5-1",
				text: "constructor",
				color: "purple",
				indent: "indent1",
				space: false,
			},
			{
				id: "code5-5-2",
				text: "(",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-5-3",
				text: "props",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-5-4",
				text: ") {",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 6行目
		[
			{
				id: "code5-6-1",
				text: "super",
				color: "red",
				indent: "indent2",
				space: false,
			},
			{
				id: "code5-6-2",
				text: "(",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-6-3",
				text: "props",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-6-4",
				text: ");",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 7行目
		[
			{
				id: "code5-7-1",
				text: "this",
				color: "red",
				indent: "indent2",
				space: false,
			},
			{
				id: "code5-7-2",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-7-3",
				text: "state",
				color: "red",
				indent: "",
				space: true,
			},
			{
				id: "code5-7-4",
				text: "= {",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 8行目
		[
			{
				id: "code5-8-1",
				text: "x",
				color: "red",
				indent: "indent3",
				space: false,
			},
			{
				id: "code5-8-2",
				text: ":",
				color: "white",
				indent: "",
				space: true,
			},
			{
				id: "code5-8-3",
				text: "0",
				color: "yellow",
				indent: "",
				space: false,
			},
			{
				id: "code5-8-4",
				text: ",",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 9行目
		[
			{
				id: "code5-9-1",
				text: "}",
				color: "white",
				indent: "indent2",
				space: false,
			},
		],
		// 10行目
		[
			{
				id: "code5-10-1",
				text: "}",
				color: "white",
				indent: "indent1",
				space: false,
			},
		],
		// 11行目
		[],
		// 12行目
		[
			{
				id: "code5-12-1",
				text: "func",
				color: "blue",
				indent: "indent1",
				space: false,
			},
			{
				id: "code5-12-2",
				text: "() {",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 13行目
		[
			{
				id: "code5-13-1",
				text: "this",
				color: "red",
				indent: "indent2",
				space: false,
			},
			{
				id: "code5-13-2",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-3",
				text: "state",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-4",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-5",
				text: "x",
				color: "red",
				indent: "",
				space: true,
			},
			{
				id: "code5-13-6",
				text: "===",
				color: "white",
				indent: "",
				space: true,
			},
			{
				id: "code5-13-7",
				text: "0",
				color: "yellow",
				indent: "",
				space: true,
			},
			{
				id: "code5-13-8",
				text: "? (",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-9",
				text: "this",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-9a",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-10",
				text: "setState",
				color: "blue",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-11",
				text: "({",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-12",
				text: "x",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-12a",
				text: ":",
				color: "white",
				indent: "",
				space: true,
			},
			{
				id: "code5-13-13",
				text: "1",
				color: "yellow",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-14",
				text: "})) : (",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-15",
				text: "this",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-16",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-17",
				text: "setState",
				color: "blue",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-18",
				text: "({",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-19",
				text: "x",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-20",
				text: ":",
				color: "white",
				indent: "",
				space: true,
			},
			{
				id: "code5-13-21",
				text: "0",
				color: "yellow",
				indent: "",
				space: false,
			},
			{
				id: "code5-13-22",
				text: "}));",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 14行目
		[
			{
				id: "code5-14-1",
				text: "}",
				color: "white",
				indent: "indent1",
				space: false,
			},
		],
		// 15行目
		[],
		// 16行目
		[
			{
				id: "code5-16-1",
				text: "render",
				color: "blue",
				indent: "indent1",
				space: false,
			},
			{
				id: "code5-16-2",
				text: "() {",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 17行目
		[
			{
				id: "code5-17-1",
				text: "return",
				color: "purple",
				indent: "indent2",
				space: true,
			},
			{
				id: "code5-17-2",
				text: "(",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 18行目
		[
			{
				id: "code5-18-1",
				text: "<",
				color: "white",
				indent: "indent3",
				space: false,
			},
			{
				id: "code5-18-2",
				text: "header",
				color: "red",
				indent: "",
				space: true,
			},
			{
				id: "code5-18-3",
				text: "className",
				color: "yellow",
				indent: "",
				space: true,
			},
			{
				id: "code5-18-4",
				text: "=\"",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-18-5",
				text: "header",
				color: "green",
				indent: "",
				space: false,
			},
			{
				id: "code5-18-6",
				text: ">",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 19行目
		[
			{
				id: "code5-19-1",
				text: "<",
				color: "white",
				indent: "indent4",
				space: false,
			},
			{
				id: "code5-19-2",
				text: "p",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-19-3",
				text: ">",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 20行目
		[
			{
				id: "code5-20-1",
				text: "{",
				color: "emerald",
				indent: "indent5",
				space: false,
			},
			{
				id: "code5-20-2",
				text: "this",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-20-3",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-20-4",
				text: "state",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-20-5",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-20-6",
				text: "x",
				color: "red",
				indent: "",
				space: true,
			},
			{
				id: "code5-20-7",
				text: "===",
				color: "white",
				indent: "",
				space: true,
			},
			{
				id: "code5-20-8",
				text: "0",
				color: "yellow",
				indent: "",
				space: true,
			},
			{
				id: "code5-20-9",
				text: "? \"",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-20-10",
				text: "Learn React",
				color: "green",
				indent: "",
				space: false,
			},
			{
				id: "code5-20-11",
				text: "\" : \"",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-20-12",
				text: "Try React",
				color: "green",
				indent: "",
				space: false,
			},
			{
				id: "code5-20-13",
				text: "\"",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-20-14",
				text: "}",
				color: "emerald",
				indent: "",
				space: false,
			},
		],
		// 21行目
		[
			{
				id: "code5-21-1",
				text: "</",
				color: "white",
				indent: "indent4",
				space: false,
			},
			{
				id: "code5-21-2",
				text: "p",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-21-3",
				text: ">",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 22行目
		[
			{
				id: "code5-22-1",
				text: "<",
				color: "white",
				indent: "indent4",
				space: false,
			},
			{
				id: "code5-22-2",
				text: "button",
				color: "red",
				indent: "",
				space: true,
			},
			{
				id: "code5-22-3",
				text: "onClick",
				color: "yellow",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-4",
				text: "=",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-5",
				text: "{",
				color: "emerald",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-6",
				text: "this",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-7",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-8",
				text: "func",
				color: "blue",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-9",
				text: ".",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-10",
				text: "bind",
				color: "brown",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-11",
				text: "(",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-12",
				text: "this",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-13",
				text: ")",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-14",
				text: "}",
				color: "emerald",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-15",
				text: ">Change State</",
				color: "white",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-16",
				text: "button",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-22-17",
				text: ">",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 23行目
		[
			{
				id: "code5-23-1",
				text: "</",
				color: "white",
				indent: "indent3",
				space: false,
			},
			{
				id: "code5-23-2",
				text: "header",
				color: "red",
				indent: "",
				space: false,
			},
			{
				id: "code5-23-3",
				text: ">",
				color: "white",
				indent: "",
				space: false,
			},
		],
		// 24行目
		[
			{
				id: "code5-24-1",
				text: ");",
				color: "white",
				indent: "indent2",
				space: false,
			},
		],
		// 25行目
		[
			{
				id: "code5-25-1",
				text: "}",
				color: "white",
				indent: "indent1",
				space: false,
			},
		],
		// 26行目
		[
			{
				id: "code5-26-1",
				text: "}",
				color: "white",
				indent: "indent",
				space: false,
			},
		],
		// 27行目
		[
			{
				id: "code5-27-1",
				text: "export default",
				color: "purple",
				indent: "",
				space: true,
			},
			{
				id: "code5-27-2",
				text: "App",
				color: "orange",
				indent: "",
				space: false,
			},
			{
				id: "code5-27-3",
				text: ";",
				color: "white",
				indent: "",
				space: false,
			},
		],
	]
}
